name: tensorflow-example
channels:
  - defaults
  - anaconda
dependencies:
  - python==3.6
  - tensorflow==1.13.1
  - numpy>=1.13.3
  - pip:
    - mlflow
    - gast
    - keras
    - tensorflow
    - numpy
